all:				Lamport.class

Lamport.class:			LamportThread.class Lamport.java
				@javac Lamport.java

LamportThread.class:		LamportThread.java
				@javac LamportThread.java

clean:
				@rm -rf *.class *~
